export {default as Home} from "./Home/Home"
export {default as Login} from "./Login/Login"
export {default as Form} from "./Form/Form"
export {default as Slide} from "./Slide/Slide"
export {default as Test} from "./Slide/Test"
export {default as Navbar} from "./Navbar/Navbar"
export {default as Layout} from "./Layout"
export {default as AllSlide} from "./Slide/AllSlide"